/**
 * @Description: Utility class to be used for storing constant
 * @Author: Rohit
 * @Class Name: ConstantUtils
 */

public with sharing class ConstantUtils {

        public static final String CLOSED = 'Closed';
        public static final String ROUTINEMAINTENANCE = 'Routine Maintenance';
        public static final String REPAIR = 'Repair';
        public static final String MAINTENANCEREQUESTHELPER = 'MaintenanceRequestHelper';
        public static final String WAREHOUSECALLOUTSERVICE = 'WarehouseCalloutService';
        public static final String NEW_CONSTANT = 'New';
        public static final String WEB = 'Web';
        public static final String CYCLE = 'cycle';
        public static final String MAINTENANCEREQUEST = 'Maintenance_Request__c';
        public static final String GET = 'GET';
        public static final String NAME = 'name';
        public static final String REPLACEMENT = 'replacement';
        public static final String MAINTENANCEPERIOD = 'maintenanceperiod';
        public static final String LIFESPAN = 'lifespan';
        public static final String SKU = 'sku';
        public static final String QUANTITY = 'quantity';
        public static final String WAREHOUSE_URL = 'https://th-superbadge-apex.herokuapp.com/equipment';
        public static final String FLS_ERROR = 'Field Acccessbilty is missing for the current user!';

}